### ISSUE TITLE
Will this recieve any update?

### ISSUE THREAD

**Issue by cifesk** [Crementif/SteamRPC#1]
I stumbled upon this again after 1 year, and last year I couldn't get this to work.

But today I tried once again, and I made some progress, but I keep getting the same error:

Error: Disconnected
    at SteamClient._disconnected (C:\Users\tiago\Desktop\eu4-discord-rich-presence-master\hoi4-discord-rich-presence\SteamRPC-master\node_modules\steam\lib\steam_client.js:189:24)
    at Connection.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:673:12)
Emitted 'error' event on SteamClient instance at:
    at SteamClient._disconnected (C:\Users\tiago\Desktop\eu4-discord-rich-presence-master\hoi4-discord-rich-presence\SteamRPC-master\node_modules\steam\lib\steam_client.js:189:10)
    at Connection.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:673:12)

Does this happen because the code is too old? Will the project recieve any update in the future?

**Comment by ghost** [comment]
oh man i dont think it will, looking at the activity in this repo...
